In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
df = pd.read_excel('../data/clean/Book1_semi.xlsx')

In [3]:
df

,pref,year,quarter,consumption_stay_all,consumption_stay_tourism,consumption_stay_home,comsumption_stay_business,consumption_day_all,consumption_day_tourism,consumption_day_home,consumption_day_business,population_stay_all,population_stay_tourism,population_stay_home,population_stay_business,population_day_all,population_day_tourism,population_day_home,population_day_business
0,Hokkaido,2018,1,189483.615,115047.168,41377.531,33058.916,30984.318,12549.801,14908.155,3526.362,3276.420,1678.891,1013.897,583.632,2019.347,935.011,795.337,288.998
1,Aomori,2018,1,21245.901,2724.858,10954.060,7566.983,1694.479,1445.383,249.096,0.000,328.631,44.493,211.429,72.710,106.427,89.937,16.490,0.000
2,Iwate,2018,1,50866.443,29084.660,13342.943,8438.839,5010.656,1858.923,1378.652,1773.081,1218.336,489.068,429.894,299.374,421.926,174.600,145.960,101.367
3,Miyagi,2018,1,74546.476,31602.533,21745.440,21198.504,12787.160,7164.855,3856.238,1766.067,1672.255,643.385,539.670,489.199,870.675,431.866,292.929,145.880
4,Akita,2018,1,17382.601,5977.363,7035.221,4370.017,6879.117,2437.399,4021.484,420.235,375.894,134.588,187.896,53.410,255.966,155.046,85.002,15.918
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,Kumamoto,2020,1,50576.800,22416.758,25731.901,2428.141,6087.825,2924.697,2810.618,352.509,965.524,375.295,565.229,25.000,540.986,270.590,221.094,49.302
419,Oita,2020,1,67562.790,42027.382,15023.393,10512.016,4497.510,3942.912,539.341,15.256,1065.743,701.460,171.402,192.881,310.076,229.990,61.704,18.381
420,Miyazaki,2020,1,30310.658,13749.582,11608.930,4952.146,4746.018,2140.963,656.029,1949.027,477.757,131.291,249.919,96.547,253.544,183.383,39.246,30.915
421,Kagoshima,2020,1,41139.990,34533.517,6606.473,0.000,3321.869,3029.067,292.802,0.000,650.847,432.955,217.892,0.000,187.902,154.800,33.102,0.000
422,Okinawa,2020,1,147315.077,120391.495,25176.691,1746.892,2640.815,1112.870,571.196,956.749,1493.224,1146.148,316.432,30.644,132.984,71.909,27.203,33.871

In [4]:
# stay_all

cpc_list = []

for i in range(423):
    consumption = df.iloc[i, 3]
    population = df.iloc[i, 11]
    
    if consumption != 0 and population != 0:
        cpc = consumption / population
    else:
        cpc = 0
        
    cpc_list.append(cpc)

In [5]:
df["cpc_stay_all"] = cpc_list

In [6]:
df

,pref,year,quarter,consumption_stay_all,consumption_stay_tourism,consumption_stay_home,comsumption_stay_business,consumption_day_all,consumption_day_tourism,consumption_day_home,consumption_day_business,population_stay_all,population_stay_tourism,population_stay_home,population_stay_business,population_day_all,population_day_tourism,population_day_home,population_day_business,cpc_stay_all
0,Hokkaido,2018,1,189483.615,115047.168,41377.531,33058.916,30984.318,12549.801,14908.155,3526.362,3276.420,1678.891,1013.897,583.632,2019.347,935.011,795.337,288.998,57.832517
1,Aomori,2018,1,21245.901,2724.858,10954.060,7566.983,1694.479,1445.383,249.096,0.000,328.631,44.493,211.429,72.710,106.427,89.937,16.490,0.000,64.649717
2,Iwate,2018,1,50866.443,29084.660,13342.943,8438.839,5010.656,1858.923,1378.652,1773.081,1218.336,489.068,429.894,299.374,421.926,174.600,145.960,101.367,41.750751
3,Miyagi,2018,1,74546.476,31602.533,21745.440,21198.504,12787.160,7164.855,3856.238,1766.067,1672.255,643.385,539.670,489.199,870.675,431.866,292.929,145.880,44.578414
4,Akita,2018,1,17382.601,5977.363,7035.221,4370.017,6879.117,2437.399,4021.484,420.235,375.894,134.588,187.896,53.410,255.966,155.046,85.002,15.918,46.243359
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,Kumamoto,2020,1,50576.800,22416.758,25731.901,2428.141,6087.825,2924.697,2810.618,352.509,965.524,375.295,565.229,25.000,540.986,270.590,221.094,49.302,52.382748
419,Oita,2020,1,67562.790,42027.382,15023.393,10512.016,4497.510,3942.912,539.341,15.256,1065.743,701.460,171.402,192.881,310.076,229.990,61.704,18.381,63.395012
420,Miyazaki,2020,1,30310.658,13749.582,11608.930,4952.146,4746.018,2140.963,656.029,1949.027,477.757,131.291,249.919,96.547,253.544,183.383,39.246,30.915,63.443671
421,Kagoshima,2020,1,41139.990,34533.517,6606.473,0.000,3321.869,3029.067,292.802,0.000,650.847,432.955,217.892,0.000,187.902,154.800,33.102,0.000,63.209925
422,Okinawa,2020,1,147315.077,120391.495,25176.691,1746.892,2640.815,1112.870,571.196,956.749,1493.224,1146.148,316.432,30.644,132.984,71.909,27.203,33.871,98.655712

In [7]:
# stay_tourism

cpc_list = []

for i in range(423):
    consumption = df.iloc[i, 4]
    population = df.iloc[i, 12]
    
    if consumption != 0 and population != 0:
        cpc = consumption / population
    else:
        cpc = 0
        
    cpc_list.append(cpc)

In [8]:
df["cpc_stay_tourism"] = cpc_list

In [9]:
# stay_home

cpc_list = []

for i in range(423):
    consumption = df.iloc[i, 5]
    population = df.iloc[i, 13]
    
    if consumption != 0 and population != 0:
        cpc = consumption / population
    else:
        cpc = 0
        
    cpc_list.append(cpc)
    
df["cpc_stay_home"] = cpc_list

In [10]:
# stay_business

cpc_list = []

for i in range(423):
    consumption = df.iloc[i, 6]
    population = df.iloc[i, 14]
    
    if consumption != 0 and population != 0:
        cpc = consumption / population
    else:
        cpc = 0
        
    cpc_list.append(cpc)
    
df["cpc_stay_business"] = cpc_list

In [11]:
# day_all

cpc_list = []

for i in range(423):
    consumption = df.iloc[i, 7]
    population = df.iloc[i, 15]
    
    if consumption != 0 and population != 0:
        cpc = consumption / population
    else:
        cpc = 0
        
    cpc_list.append(cpc)
    
df["cpc_day_all"] = cpc_list

In [12]:
# day_tourism

cpc_list = []

for i in range(423):
    consumption = df.iloc[i, 8]
    population = df.iloc[i, 16]
    
    if consumption != 0 and population != 0:
        cpc = consumption / population
    else:
        cpc = 0
        
    cpc_list.append(cpc)
    
df["cpc_day_tourism"] = cpc_list

In [13]:
# day_home

cpc_list = []

for i in range(423):
    consumption = df.iloc[i, 9]
    population = df.iloc[i, 17]
    
    if consumption != 0 and population != 0:
        cpc = consumption / population
    else:
        cpc = 0
        
    cpc_list.append(cpc)
    
df["cpc_day_home"] = cpc_list

In [14]:
# day_business

cpc_list = []

for i in range(423):
    consumption = df.iloc[i, 10]
    population = df.iloc[i, 18]
    
    if consumption != 0 and population != 0:
        cpc = consumption / population
    else:
        cpc = 0
        
    cpc_list.append(cpc)
    
df["cpc_day_business"] = cpc_list

In [15]:
df

,pref,year,quarter,consumption_stay_all,consumption_stay_tourism,consumption_stay_home,comsumption_stay_business,consumption_day_all,consumption_day_tourism,consumption_day_home,...,population_day_home,population_day_business,cpc_stay_all,cpc_stay_tourism,cpc_stay_home,cpc_stay_business,cpc_day_all,cpc_day_tourism,cpc_day_home,cpc_day_business
0,Hokkaido,2018,1,189483.615,115047.168,41377.531,33058.916,30984.318,12549.801,14908.155,...,795.337,288.998,57.832517,68.525692,40.810389,56.643426,15.343731,13.422089,18.744450,12.202029
1,Aomori,2018,1,21245.901,2724.858,10954.060,7566.983,1694.479,1445.383,249.096,...,16.490,0.000,64.649717,61.242398,51.809638,104.070733,15.921514,16.071061,15.105882,0.000000
2,Iwate,2018,1,50866.443,29084.660,13342.943,8438.839,5010.656,1858.923,1378.652,...,145.960,101.367,41.750751,59.469563,31.037751,28.188283,11.875675,10.646753,9.445410,17.491698
3,Miyagi,2018,1,74546.476,31602.533,21745.440,21198.504,12787.160,7164.855,3856.238,...,292.929,145.880,44.578414,49.119163,40.293957,43.333089,14.686490,16.590459,13.164412,12.106300
4,Akita,2018,1,17382.601,5977.363,7035.221,4370.017,6879.117,2437.399,4021.484,...,85.002,15.918,46.243359,44.412303,37.442101,81.820202,26.875120,15.720489,47.310463,26.399987
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,Kumamoto,2020,1,50576.800,22416.758,25731.901,2428.141,6087.825,2924.697,2810.618,...,221.094,49.302,52.382748,59.731033,45.524736,97.125640,11.253202,10.808592,12.712321,7.149994
419,Oita,2020,1,67562.790,42027.382,15023.393,10512.016,4497.510,3942.912,539.341,...,61.704,18.381,63.395012,59.914153,87.650045,54.500008,14.504541,17.143841,8.740779,0.829987
420,Miyazaki,2020,1,30310.658,13749.582,11608.930,4952.146,4746.018,2140.963,656.029,...,39.246,30.915,63.443671,104.726006,46.450770,51.292593,18.718715,11.674817,16.715818,63.044703
421,Kagoshima,2020,1,41139.990,34533.517,6606.473,0.000,3321.869,3029.067,292.802,...,33.102,0.000,63.209925,79.762370,30.319943,0.000000,17.678731,19.567616,8.845447,0.000000
422,Okinawa,2020,1,147315.077,120391.495,25176.691,1746.892,2640.815,1112.870,571.196,...,27.203,33.871,98.655712,105.040095,79.564301,57.006004,19.858141,15.476088,20.997537,28.246848

In [16]:
df = df.drop(columns=['consumption_stay_all', 'consumption_stay_tourism', 'consumption_stay_home', 'comsumption_stay_business', 'consumption_day_all',
                 'consumption_day_tourism', 'consumption_day_home', 'consumption_day_business', 'population_stay_all', 'population_stay_tourism',
                'population_stay_home', 'population_stay_business', 'population_day_all', 'population_day_tourism', 'population_day_home',
                'population_day_business'])

In [17]:
df.to_stata('../csv/for_analysis/main_domestic.dta')